//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tiny_Tile_Editor.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Tiny_Tile_Editor.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap about {
            get {
                object obj = ResourceManager.GetObject("about", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiny Tile Editor.
        /// </summary>
        internal static string ApplicationName {
            get {
                return ResourceManager.GetString("ApplicationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string Caption_About {
            get {
                return ResourceManager.GetString("Caption_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation.
        /// </summary>
        internal static string Caption_Confirmation {
            get {
                return ResourceManager.GetString("Caption_Confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Caption_Error {
            get {
                return ResourceManager.GetString("Caption_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        internal static string Caption_Information {
            get {
                return ResourceManager.GetString("Caption_Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string Caption_Status {
            get {
                return ResourceManager.GetString("Caption_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tips.
        /// </summary>
        internal static string Caption_Tips {
            get {
                return ResourceManager.GetString("Caption_Tips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsaved Changes.
        /// </summary>
        internal static string Caption_Unsaved_Changes {
            get {
                return ResourceManager.GetString("Caption_Unsaved_Changes", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap clear_active_layer {
            get {
                object obj = ResourceManager.GetObject("clear_active_layer", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap clear_collision_layer {
            get {
                object obj = ResourceManager.GetObject("clear_collision_layer", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap clear_map {
            get {
                object obj = ResourceManager.GetObject("clear_map", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap edit_tile_types {
            get {
                object obj = ResourceManager.GetObject("edit_tile_types", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap exit {
            get {
                object obj = ResourceManager.GetObject("exit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap layer_down {
            get {
                object obj = ResourceManager.GetObject("layer_down", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap layer_up {
            get {
                object obj = ResourceManager.GetObject("layer_up", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap map_new {
            get {
                object obj = ResourceManager.GetObject("map_new", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap map_open {
            get {
                object obj = ResourceManager.GetObject("map_open", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap map_save {
            get {
                object obj = ResourceManager.GetObject("map_save", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap map_save_as {
            get {
                object obj = ResourceManager.GetObject("map_save_as", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap marker__minus {
            get {
                object obj = ResourceManager.GetObject("marker__minus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap redo {
            get {
                object obj = ResourceManager.GetObject("redo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap show_collision_layer {
            get {
                object obj = ResourceManager.GetObject("show_collision_layer", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap show_grid {
            get {
                object obj = ResourceManager.GetObject("show_grid", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap show_other_layers {
            get {
                object obj = ResourceManager.GetObject("show_other_layers", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Made by Dylan Peinhardt
        ///
        ///Email: peinhardtd@gmail.com
        ///
        ///Site: http://code.google.com/p/tiny-tile-editor/
        ///
        ///Version 2.0
        ///
        ///Copyright 2011 Dylan Peinhardt.
        /// </summary>
        internal static string Text_About {
            get {
                return ResourceManager.GetString("Text_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot edit the default tile type..
        /// </summary>
        internal static string Text_Cannot_Edit_Default_Tile_Type {
            get {
                return ResourceManager.GetString("Text_Cannot_Edit_Default_Tile_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot remove the default tile type..
        /// </summary>
        internal static string Text_Cannot_Remove_Default_Tile_Type {
            get {
                return ResourceManager.GetString("Text_Cannot_Remove_Default_Tile_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this tile type?.
        /// </summary>
        internal static string Text_Confirm_Delete_Tile_Type {
            get {
                return ResourceManager.GetString("Text_Confirm_Delete_Tile_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This identifier is already in use. Please choose another..
        /// </summary>
        internal static string Text_Identifier_In_Use {
            get {
                return ResourceManager.GetString("Text_Identifier_In_Use", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a negative numerical tile identifier..
        /// </summary>
        internal static string Text_Invalid_Tile_Type_Identifier {
            get {
                return ResourceManager.GetString("Text_Invalid_Tile_Type_Identifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid name for the tile type..
        /// </summary>
        internal static string Text_Invalid_Tile_Type_Name {
            get {
                return ResourceManager.GetString("Text_Invalid_Tile_Type_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map file saved successfully!.
        /// </summary>
        internal static string Text_Map_Saved {
            get {
                return ResourceManager.GetString("Text_Map_Saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this tile type? This operation will remove all tiles of that type from the map. This process cannot be un-done..
        /// </summary>
        internal static string Text_Remove_Tile_Type {
            get {
                return ResourceManager.GetString("Text_Remove_Tile_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use the mouse wheel to vertically scroll the displays. Shift + mouse wheel scrolls horizontally.
        ///
        ///Use the QWE to quickly switch between tools.
        ///
        ///A and S shift the current layer down and up, respectively.
        ///
        ///Undo and redo work when changing the map&apos;s dimensions and after editing tile types.
        ///
        ///Click the alternate mouse button to cancel the current drawing operation.
        ///
        ///Try dragging tilesets and map files in to their corresponding display for loading..
        /// </summary>
        internal static string Text_Tips {
            get {
                return ResourceManager.GetString("Text_Tips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This will erase the entire map. Are you sure?.
        /// </summary>
        internal static string Text_Warning_Erase_Map {
            get {
                return ResourceManager.GetString("Text_Warning_Erase_Map", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap tileset_load {
            get {
                object obj = ResourceManager.GetObject("tileset_load", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap tips {
            get {
                object obj = ResourceManager.GetObject("tips", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap tool_brush {
            get {
                object obj = ResourceManager.GetObject("tool_brush", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap tool_collision {
            get {
                object obj = ResourceManager.GetObject("tool_collision", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap tool_fill {
            get {
                object obj = ResourceManager.GetObject("tool_fill", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap tool_marquee {
            get {
                object obj = ResourceManager.GetObject("tool_marquee", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap undo {
            get {
                object obj = ResourceManager.GetObject("undo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
